name: Android CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Run tests
        run: bash ./gradlew test --stacktrace

  build:
    name: Build Project
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build debug APK
        run: |
          bash ./gradlew assembleDebug --stacktrace
          tree ./app/build/outputs

      - name: Get latest Git tag
        run: |
          if git describe --tags --abbrev=0 >/dev/null 2>&1; then
            echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          else
            echo "GIT_TAG=untagged" >> $GITHUB_ENV
          fi

      - name: Get git hash
        shell: bash
        run: |
          echo ${{ github.sha }}
          echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV
          echo "GITHUB_SHA_7=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Upload Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: Midas-${{ env.GIT_TAG }}-${{ env.GITHUB_SHA_7 }}-debug.apk
          path: ./app/build/outputs/apk/debug/Midas-${{ env.GIT_TAG }}-${{ env.GITHUB_SHA_7 }}-debug.apk
