name: Generate Release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Run tests
        run: bash ./gradlew test --stacktrace

  release:
    name: Generate Release
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Decode keystore
        run: |
          echo "${{ secrets.MIDAS_KEYSTORE }}" | base64 --decode > app/midas.jks

      - name: Build da APK de release
        env:
          KEYSTORE_PATH: midas.jks
          KEYSTORE_PASSWORD: ${{ secrets.MIDAS_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.MIDAS_KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.MIDAS_KEY_PASSWORD }}
        run: |
          ./gradlew assembleRelease --stacktrace

      - name: Get latest Git tag
        run: echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Upload Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: Midas-${{ env.GIT_TAG }}-release.apk
          path: ./app/build/outputs/apk/release/Midas-${{ env.GIT_TAG }}-release.apk

      - name: Release with Changelog
        id: release-with-changelog
        uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.MIDAS_RELEASE }}
          exclude: '^Meta'
          commit-template: '- {title} ← {hash}'
          template: |
            ### Changelog

            {commits}

            {range}

      - name: Upload Release APK
        id: upload-release-apk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MIDAS_RELEASE }}
        with:
          upload_url: ${{ steps.release-with-changelog.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./app/build/outputs/apk/release/Midas-${{ env.GIT_TAG }}-release.apk
          asset_name: Midas-${{ env.GIT_TAG }}-release.apk
          asset_content_type: application/apk