name: Generate Release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release:
    name: Generate Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Rename generated APK
        shell: bash
        run: |
          cd ./app/build/outputs/apk/debug/
          mv *.apk Midas-${{ github.ref_name }}.apk
          ls -l

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: Midas-${{ github.ref_name }}.apk
          path: ./app/build/outputs/apk/debug/

      - name: Release with changelog
        uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.MIDAS_RELEASE }}
          exclude: '^Meta'
          commit-template: '- {title} ← {hash}'
          template: |
            ### Changelog

            {commits}

            {range}

      - name: Upload Release Apk
        id: upload-release-pdk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MIDAS_RELEASE}}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./app/build/outputs/apk/debug/
          asset_name: Midas-${{ github.ref_name }}.apk
          asset_content_type: application/apk