name: Generate Release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release:
    name: Generate Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Rename generated APK
        shell: bash
        run: |
          cd ./app/build/outputs/apk/debug/
          mv *.apk Midas-${{ github.ref_name }}.apk
          ls -l

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-artifact@v4
        with:
          name: Midas-${{ github.ref_name }}.apk
          path: ./app/build/outputs/apk/debug/

      - name: Release with changelog
        uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.MIDAS_RELEASE }}
          exclude: '^Meta'
          commit-template: '- {title} ← {hash}'
          template: |
            ### Changelog

            {commits}

            {range}

            ❤
